repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        language: system
        entry: env PYTHONPATH=. pylint
        files: ^(app|common|\.)/.*\.py$
        types: [python]
        args: [--disable=W0511]
